### ISSUE TITLE
Documentation web site doesn't work under Chrome/Linux

### ISSUE THREAD

**Issue by nevkontakte** [bradley/Blotter#41]
This is how the page renders: ![screenshot](https://user-images.githubusercontent.com/574640/60756289-d3281700-9ff3-11e9-959a-8f711a46d31b.png). As you can see, most of the content is missing.

There seems to be an error in the dev console, which I suspect to be the cause:
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
3blotter-site.min.js:32 THREE.WebGLRenderer 89
3blotter-site.min.js:32 Uncaught DOMException: Failed to construct 'ImageData': The input data length is not a multiple of 4.
    at a.Renderer.setSize (https://blotter.js.org/dist/blotter-site.min.js:32:402713)
    at a.Renderer.set width [as width] (https://blotter.js.org/dist/blotter-site.min.js:32:401862)
    at a.<anonymous> (https://blotter.js.org/dist/blotter-site.min.js:32:351011)
    at D (https://blotter.js.org/dist/blotter-site.min.js:32:7597)
    at https://blotter.js.org/dist/blotter-site.min.js:32:7799
    at https://blotter.js.org/dist/blotter-site.min.js:32:1228
    at a.<anonymous> (https://blotter.js.org/dist/blotter-site.min.js:32:350724)
    at D (https://blotter.js.org/dist/blotter-site.min.js:32:7597)
    at https://blotter.js.org/dist/blotter-site.min.js:32:7799
    at https://blotter.js.org/dist/blotter-site.min.js:32:1228
```

**Comment by briangbrown** [comment]
Similar error on Chrome/Windows. Loading https://blotter.js.org/#/basics

Uncaught DOMException: Failed to construct 'ImageData': The input data length is not a multiple of 4.
    at a.Renderer.setSize (https://blotter.js.org/dist/blotter-site.min.js:32:402713)
    at a.Renderer.set width [as width] (https://blotter.js.org/dist/blotter-site.min.js:32:401862)
    at a.<anonymous> (https://blotter.js.org/dist/blotter-site.min.js:32:351011)
    at D (https://blotter.js.org/dist/blotter-site.min.js:32:7597)
    at https://blotter.js.org/dist/blotter-site.min.js:32:7799
    at https://blotter.js.org/dist/blotter-site.min.js:32:1228
    at a.<anonymous> (https://blotter.js.org/dist/blotter-site.min.js:32:350724)
    at D (https://blotter.js.org/dist/blotter-site.min.js:32:7597)
    at https://blotter.js.org/dist/blotter-site.min.js:32:7799
    at https://blotter.js.org/dist/blotter-site.min.js:32:1228

Also this deprecation warning:
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:2
